apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-app
      image: nginx:1.12-alpine
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
