apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxOTIuMTY4LjEuMzo4MTIzIjp7InVzZXJuYW1lIjoiamVua2lucyIsInBhc3N3b3JkIjoiamVua2lucyIsImVtYWlsIjoiZW1haWxAZXhhbXBsZS5jb20iLCJhdXRoIjoiYW1WdWEybHVjenBxWlc1cmFXNXoifX19
type: kubernetes.io/dockerconfigjson

