version: "2.4"
services:
  jenkins:
    build: .
    ports:
      - 8080:8080
    volumes:
      - /opt/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-docker-network
networks:
  my-docker-network:
    ipam:
      driver: default
      config:
        - subnet: 10.200.200.0/24
